plugins { id 'com.android.application' }
android {
    namespace 'vn.lekhaccong.congviecteam'
    compileSdk 35
    defaultConfig {
        applicationId 'vn.lekhaccong.congviecteam'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
